name: Deploy Protected Site

on:
  push:
    branches:
      - main  # Or 'master' depending on your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Inject Secrets into HTML
        run: |
          sed -i 's/\[\[API_KEY\]\]/${{ secrets.FIREBASE_API_KEY }}/g' index.html
          sed -i 's/\[\[AUTH_DOMAIN\]\]/${{ secrets.FIREBASE_AUTH_DOMAIN }}/g' index.html
          sed -i 's/\[\[PROJECT_ID\]\]/${{ secrets.FIREBASE_PROJECT_ID }}/g' index.html
          sed -i 's/\[\[STORAGE_BUCKET\]\]/${{ secrets.FIREBASE_STORAGE_BUCKET }}/g' index.html
          sed -i 's/\[\[MESSAGING_SENDER_ID\]\]/${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}/g' index.html
          sed -i 's/\[\[APP_ID\]\]/${{ secrets.FIREBASE_APP_ID }}/g' index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # The folder the action should deploy.
          branch: gh-pages # The branch the action should deploy to.
